# Generated by Django 3.1.6 on 2021-03-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleJoinedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(verbose_name='Straipsnio pavadinimas')),
                ('article_url', models.TextField(verbose_name='Straipsnio nuoroda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('points', models.IntegerField(verbose_name='points')),
                ('type', models.CharField(choices=[('testas', 'testas'), ('straipsnis', 'straipsnis'), ('renginys', 'renginys'), ('papildoma', 'papildoma')], max_length=50, verbose_name='type')),
                ('multiple', models.BooleanField(help_text='can the participant join this challenge more than once', verbose_name='multiple')),
                ('needs_confirmation', models.BooleanField(help_text='if completion of this challenge needs to be confirmed by admins', verbose_name='required confirmation by admin')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipantChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=1000, verbose_name='event name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link to the event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipantJoinedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'joined'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=255)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge')),
            ],
        ),
    ]
