# Generated by Django 3.1.6 on 2021-03-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedchallenge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='eventparticipantjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AddField(
            model_name='eventparticipantchallenge',
            name='main_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge'),
        ),
        migrations.AddField(
            model_name='eventparticipantchallenge',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='articlejoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AddField(
            model_name='articlechallenge',
            name='main_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge'),
        ),
    ]
