# Generated by Django 3.1.6 on 2021-07-16 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '__first__'),
        ('challenge', '0002_auto_20210713_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz', verbose_name='quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
