# Generated by Django 3.1.6 on 2021-03-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0002_auto_20210318_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlechallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventparticipantchallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='joinedchallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='articlechallenge',
            name='main_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge'),
        ),
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='article_name',
            field=models.TextField(verbose_name='name of the article'),
        ),
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='article_url',
            field=models.TextField(verbose_name='link to the article'),
        ),
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='eventparticipantchallenge',
            name='main_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge'),
        ),
        migrations.AlterField(
            model_name='eventparticipantjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='joinedchallenge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='joinedchallenge',
            name='status',
            field=models.CharField(choices=[('joined', 'joined'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='joinedchallenge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
