# Generated by Django 3.1.6 on 2021-03-27 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210327_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlejoinedchallenge',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventparticipantjoinedchallenge',
            name='id',
        ),
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventparticipantjoinedchallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
