# Generated by Django 3.1.6 on 2021-03-18 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20210318_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlejoinedchallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventparticipantjoinedchallenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
