# Generated by Django 3.1.6 on 2021-07-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210721_1651'),
        ('challenge', '0003_customchallenge_quizchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchallenge',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz', verbose_name='quiz'),
        ),
    ]
