# Generated by Django 3.1.6 on 2021-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20210327_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='article_name',
            field=models.TextField(blank=True, null=True, verbose_name='name of the article'),
        ),
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='article_url',
            field=models.URLField(blank=True, null=True, verbose_name='link to the article'),
        ),
    ]
