# Generated by Django 3.1.6 on 2021-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20210318_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('quiz', 'quiz'), ('article', 'article'), ('event', 'event'), ('custom', 'custom')], max_length=50, verbose_name='type'),
        ),
    ]
