# Generated by Django 3.1.6 on 2021-04-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20210401_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipantchallenge',
            name='region',
        ),
        migrations.AddField(
            model_name='challenge',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.region', verbose_name='region'),
        ),
    ]
