# Generated by Django 3.1.6 on 2021-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20210721_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
