# Generated by Django 3.1.6 on 2021-04-08 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20210408_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
        ),
    ]
