# Generated by Django 3.1.6 on 2021-03-24 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20210318_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
