# Generated by Django 3.1.6 on 2021-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='price',
            field=models.IntegerField(default=1, verbose_name='price'),
            preserve_default=False,
        ),
    ]
