# Generated by Django 3.2.9 on 2021-11-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20210921_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipantchallenge',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR code'),
        ),
        migrations.AddField(
            model_name='eventparticipantchallenge',
            name='qr_code_file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR code file'),
        ),
    ]
