# Generated by Django 3.2.9 on 2021-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20211108_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipantchallenge',
            name='qr_code_file',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodesimages', verbose_name='QR code file'),
        ),
    ]
