# Generated by Django 3.2.9 on 2022-04-09 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_alter_eventparticipantchallenge_qr_code_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchallenge',
            name='quiz',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.quizchallenge', verbose_name='quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name='answer')),
                ('correct', models.BooleanField(default=False, verbose_name='correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.question', verbose_name='question')),
            ],
        ),
    ]
