# Generated by Django 3.1.6 on 2021-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_claimedprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
    ]
