# Generated by Django 3.1.6 on 2021-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_challenge_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
