# Generated by Django 3.2.9 on 2022-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20220409_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipantchallenge',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='QR code'),
        ),
    ]
