# Generated by Django 4.2 on 2024-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_alter_eventparticipantchallenge_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='name',
            new_name='_name',
        ),
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
