# Generated by Django 3.1.6 on 2021-05-13 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20210505_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('quiz', 'quiz'), ('article', 'article'), ('event', 'event'), ('custom', 'custom'), ('school_gsa', 'school GSA'), ('event_org', 'event organizer'), ('story', 'story'), ('project', 'project'), ('reacting', 'reacting to public events, informing society'), ('support', 'support')], max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='joinedchallenge',
            name='status',
            field=models.CharField(choices=[('joined', 'joined'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='joined', max_length=255, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='SupportJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('other_organization', models.CharField(blank=True, help_text='only if organization on challenge is Other', max_length=1000, null=True, verbose_name='Other organization')),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=1000, null=True, verbose_name='organization')),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_url', models.URLField(blank=True, null=True, verbose_name='link to the story if it has one')),
                ('description', models.TextField(verbose_name='description of your story')),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolGSAJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolGSAChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactingJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_description', models.TextField(verbose_name='description of the reaction in your own words')),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactingChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.TextField(blank=True, null=True, verbose_name='name of the event')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='link to the event website or Facebook page if there is one')),
                ('project_description', models.TextField(verbose_name='description of the event in your own words')),
                ('implemented_alone', models.BooleanField(blank=True, null=True, verbose_name='if this event was implemented by you alone')),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventOrganizerJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.TextField(blank=True, null=True, verbose_name='name of the event')),
                ('event_url', models.URLField(blank=True, null=True, verbose_name='link to the event website or Facebook page if there is one')),
                ('event_description', models.TextField(verbose_name='description of the event in your own words')),
                ('organized_alone', models.BooleanField(blank=True, null=True, verbose_name='if this event was organized by you alone')),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventOrganizerChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge', verbose_name='main challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
