# Generated by Django 3.1.6 on 2021-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20210513_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='joinedchallenge',
            name='status',
            field=models.CharField(choices=[('joined', 'joined'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed')], default='joined', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='projectjoinedchallenge',
            name='implemented_alone',
            field=models.BooleanField(blank=True, null=True, verbose_name='if this project was implemented by you alone'),
        ),
    ]
