# Generated by Django 4.2 on 2024-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_remove_topic_topic_en_remove_topic_topic_lt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_en',
            field=models.CharField(max_length=255, null=True, verbose_name='topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='topic'),
        ),
    ]
