# Generated by Django 4.2 on 2024-06-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_challenge__name_en_challenge__name_lt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='_name_en',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='_name_lt',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='_name_pt',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='_name_sk',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description_lt',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description_pt',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description_sk',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='published_en',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='published_lt',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='published_pt',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='published_sk',
        ),
        migrations.RemoveField(
            model_name='eventparticipantchallenge',
            name='event_name_en',
        ),
        migrations.RemoveField(
            model_name='eventparticipantchallenge',
            name='event_name_lt',
        ),
        migrations.RemoveField(
            model_name='eventparticipantchallenge',
            name='event_name_pt',
        ),
        migrations.RemoveField(
            model_name='eventparticipantchallenge',
            name='event_name_sk',
        ),
        migrations.RemoveField(
            model_name='supportchallenge',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='supportchallenge',
            name='organization_lt',
        ),
        migrations.RemoveField(
            model_name='supportchallenge',
            name='organization_pt',
        ),
        migrations.RemoveField(
            model_name='supportchallenge',
            name='organization_sk',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_lt',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_pt',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_sk',
        ),
    ]
