# Generated by Django 4.2 on 2024-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0021_challenge__name_en_challenge__name_lt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_lt',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_pt',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_sk',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_lt',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_pt',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_sk',
            field=models.TextField(null=True, verbose_name='question'),
        ),
    ]
