# Generated by Django 3.1.6 on 2021-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lgbt',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('prefer_not_to_say', 'prefer not to say')], max_length=255, null=True, verbose_name='are you lgbt?'),
        ),
    ]
