# Generated by Django 3.1.6 on 2021-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210318_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'woman'), ('man', 'man'), ('non-binary', 'non-binary'), ('other', 'other'), ('prefer_not_to_say', 'prefer not to say')], max_length=255, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='enter gender if selected other'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.IntegerField(default=2021, verbose_name='year of birth'),
            preserve_default=False,
        ),
    ]
