# Generated by Django 3.1.6 on 2021-03-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_region_uuid'),
        ('user', '0003_auto_20210318_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.region', verbose_name='region'),
        ),
    ]
