# Generated by Django 3.1.6 on 2021-04-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_prize'),
        ('user', '0003_auto_20210408_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.region', verbose_name='region'),
        ),
    ]
