# Generated by Django 3.1.6 on 2021-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210408_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'woman'), ('man', 'man'), ('non-binary', 'non-binary'), ('other', 'other'), ('prefer_not_to_say', 'prefer not to say')], max_length=255, null=True, verbose_name='gender'),
        ),
    ]
