# Generated by Django 4.1 on 2022-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marked_for_deletion',
            field=models.BooleanField(default=False, verbose_name='marked for deletion'),
        ),
    ]
