# Generated by Django 3.2.16 on 2023-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_marked_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marked_for_deletion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date and time when marked for deletion'),
        ),
    ]
