# Generated by Django 4.2 on 2024-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsitem_body_en_remove_newsitem_body_lt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='body_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='body_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='body_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_lt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_pt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_sk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_lt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_pt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_sk',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
