# Generated by Django 4.2 on 2024-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_remove_text_id_text_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='body_en',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='text',
            name='body_lt',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='text',
            name='body_pt',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='text',
            name='body_sk',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='text',
            name='notes_en',
            field=models.TextField(null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='text',
            name='notes_lt',
            field=models.TextField(null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='text',
            name='notes_pt',
            field=models.TextField(null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='text',
            name='notes_sk',
            field=models.TextField(null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='text',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='text',
            name='title_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='text',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='text',
            name='title_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
