# Generated by Django 3.1.6 on 2021-07-13 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joined_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedchallenge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='eventparticipantjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AddField(
            model_name='eventorganizerjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AddField(
            model_name='articlejoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
    ]
