# Generated by Django 3.1.6 on 2021-07-16 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0002_auto_20210713_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizerjoinedchallenge',
            name='organized_alone',
            field=models.BooleanField(blank=True, null=True, verbose_name='was this event was organized by you alone'),
        ),
        migrations.CreateModel(
            name='QuizJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomJoinedChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='description')),
                ('main_joined_challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
