# Generated by Django 3.1.6 on 2021-07-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210721_1651'),
        ('joined_challenge', '0003_auto_20210716_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizjoinedchallenge',
            name='quiz_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizuser', verbose_name='quiz user object'),
            preserve_default=False,
        ),
    ]
