# Generated by Django 3.1.6 on 2021-09-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210721_1651'),
        ('joined_challenge', '0004_quizjoinedchallenge_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedchallenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='joinedchallenge',
            name='status',
            field=models.CharField(choices=[('joined', 'joined'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed')], default='joined', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='quizjoinedchallenge',
            name='quiz_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizuser', verbose_name='quiz user object'),
        ),
    ]
