# Generated by Django 3.2.9 on 2021-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0005_auto_20210907_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipantjoinedchallenge',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR code'),
        ),
    ]
