# Generated by Django 3.2.9 on 2021-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0006_eventparticipantjoinedchallenge_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customjoinedchallenge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventorganizerjoinedchallenge',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='description of the event in your own words'),
        ),
        migrations.AlterField(
            model_name='projectjoinedchallenge',
            name='project_description',
            field=models.TextField(blank=True, null=True, verbose_name='description of the event in your own words'),
        ),
        migrations.AlterField(
            model_name='reactingjoinedchallenge',
            name='reaction_description',
            field=models.TextField(blank=True, null=True, verbose_name='description of the reaction in your own words'),
        ),
        migrations.AlterField(
            model_name='storyjoinedchallenge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of your story'),
        ),
    ]
