# Generated by Django 3.2.9 on 2021-11-30 19:04

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0007_auto_20211123_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedChallengeFile',
            fields=[
                ('file', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='joined_challenge_files', verbose_name='file')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='joined challenge')),
            ],
        ),
    ]
