# Generated by Django 3.2.9 on 2021-12-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0008_joinedchallengefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlejoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='customjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='eventorganizerjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='eventparticipantjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='projectjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='quizjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='reactingjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='schoolgsajoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='storyjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
        migrations.AlterField(
            model_name='supportjoinedchallenge',
            name='main_joined_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joined_challenge.joinedchallenge', verbose_name='main joined challenge'),
        ),
    ]
