# Generated by Django 3.2.9 on 2021-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0010_articlejoinedchallenge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedchallenge',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='joined at'),
        ),
    ]
