# Generated by Django 3.2.9 on 2022-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joined_challenge', '0011_joinedchallenge_joined_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventorganizerjoinedchallenge',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectjoinedchallenge',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reactingjoinedchallenge',
            old_name='reaction_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='supportjoinedchallenge',
            name='other_organization',
        ),
        migrations.AddField(
            model_name='schoolgsajoinedchallenge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of the reaction in your own words'),
        ),
        migrations.AddField(
            model_name='supportjoinedchallenge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of support'),
        ),
    ]
