# Generated by Django 3.2.9 on 2022-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211126_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('medal', 'Medal'), ('challenge_confirmation', 'Challenge Confirmation')], max_length=255, null=True, verbose_name='type'),
        ),
    ]
